version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on localhost
    command: ["redis-server", "--bind", "0.0.0.0"]
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080" # Expose Spring Boot app on localhost
    depends_on:
      - mongodb
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
